FROM python:3.8.20

WORKDIR /mmdetection 

COPY . /mmdetection 

# 필요한 시스템 종속성 설치
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0

# pip 업그레이드
RUN pip install --upgrade pip

# PyTorch 및 torchvision CPU 버전 설치
RUN pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cpu

# openmim 설치
RUN pip install -U openmim

# MMEngine 0.10.5 설치
RUN mim install mmengine

# MMCV 2.1.0 설치 (CPU 환경)
RUN pip install mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cpu/torch2.0/index.html

# 기타 종속성 설치
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]
