FROM python:3.8.20

WORKDIR /mmdetection 

COPY . /mmdetection 

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0

RUN pip install --upgrade pip

RUN pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cpu

RUN pip install -U openmim

RUN mim install mmengine

RUN pip install mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cpu/torch2.0/index.html

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]
